version: "3.9"

services:
  # Production service (default)
  api:
    image: nasa-data-explorer-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    environment:
      - NODE_ENV=production
      - PORT=8000
      - NASA_API_KEY=${NASA_API_KEY}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Development service (enabled with --profile dev)
  api-dev:
    profiles: ["dev"]
    image: nasa-data-explorer-backend:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - NODE_ENV=development
      - PORT=8000
      - NASA_API_KEY=${NASA_API_KEY}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
    ports:
      - "8000:8000"
    # Mount source for live reload; keep node_modules inside container
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
    restart: unless-stopped
